export const external = [
  '@teamwork/websocket-json-stream',
  'express',
  'jsesc',
  //'ot-json1',
  'react',
  'react-dom',
  'sharedb',
  'sharedb/lib/client',
  'ws',
  'http',
  'react-dom/server',
  'diff-match-patch',
  'json0-ot-diff',
  //'ot-text-unicode',
  'sharedb-mingo-memory',
  'mocha',
  'sharedb',
  'assert',
  'mocha',
  'react-bootstrap',
  'vizhub-ui',
];

export const globals = {
  react: 'React',
  'react-dom': 'ReactDOM',
  'sharedb/lib/client': 'ShareDBClient',
  'react-bootstrap': 'ReactBootstrap',
  'vizhub-ui': 'VizHubUI',
};
